#!/bin/bash
# Script for building ios and android applications
# Adam Cockell
# January 2014

platform=$1
for_app=$2
build_directory_a=$3
build_directory_b=$4
build_directory_c=$5

original_directory=($(pwd))

if [[ -z $build_directory_b ]]; then
  echo "skipping directory B build"
else
  cd $build_directory_b
  if [ "$platform" == "ios" ]; then
    xcrun xcodebuild -target R1PhotoEffectsSDK -sdk iphoneos "ARCHS=armv7s armv7" IPHONEOS_DEPLOYMENT_TARGET=5.0 clean build
  else
    if [[ -z $build_directory_c ]]; then
      echo "You did not specify the relative SDK path"
      exit
    fi
    clean_all
    android update project --target "android-17" --path .
    ant clean release
  fi
  cd $original_directory
fi

if [[ -z $build_directory_a ]]; then 
  echo "skipping directory A build"
else
  cd $build_directory_a
  if [ "$platform" == "ios" ]; then
    xcrun xcodebuild -target $for_app -sdk iphoneos "ARCHS=armv7s armv7" clean build CODE_SIGN_IDENTITY="iPhone Developer: Brad Smith (YE9V76353E)"
    "$original_directory/fruitstrap" -i $udid -b build/Release-iphoneos/Demo.app
  else
    clean_all
    if [[ -z $build_directory_b ]]; then
      android update project --target "android-17" --path .
    else
      android update project --target "android-17" --path . --library $build_directory_c
    fi
    ant debug
    adb install -r bin/*.apk
  fi
  cd $original_directory
fi

