#!/bin/bash
# Script for validating custom SDK builds
# Adam Cockell
# January 2014

platform=$1
for_app=$2
for_version=$3
qa_line_a=$4
qa_line_b=$5
feature=$6
build_directory_a=$7
build_directory_b=$8
build_directory_c=$9

write_app()
{
  VERSION_TESTING=$1
  QA_LINE_A=$2
  QA_LINE_B=$3
  FEATURE=$4

  if [ "$VERSION_TESTING" != "" ]; then
    # clone git repo and checkout older build
    [ ! -d temp_build ] || rm -r -f temp_build
    git clone git@github.com:viame/r1-effects-sdk-ios.git temp_build
    cd temp_build
    git checkout $VERSION_TESTING
    git submodule init
    git submodule update

    cd ..
    ./build $platform $for_app $build_directory_a temp_build
    rm -r -f temp_build
    ./cucumber $platform $for_app build_regression

    # rebuild the sdk
    ./cucumber $platform $for_app $feature $build_directory_a $build_directory_b
  else
    # apply customization to current build
    echo "Modifying $for_app for crop selection"
    sed "s/QA_LINE_A/$QA_LINE_A/g" "automation/AppDelegateTemplate.m" > "automation/AppDelegateTemplateB.m"

    echo "Modifying $for_app for effects selection"
    sed "s/QA_LINE_B/$QA_LINE_B/g" "automation/AppDelegateTemplateB.m" > $build_directory_a/$for_app/AppDelegate.m
    rm "automation/AppDelegateTemplateB.m"
  
    # rebuild the app only
    ./cucumber $platform $for_app $feature $build_directory_a

    # cleanup appdelegate
    git checkout $build_directory_a/$for_app/AppDelegate.m

  fi
}

write_app "$for_version" "$qa_line_a" "$qa_line_b" "$feature"
