#!/bin/bash
# Script for validating custom SDK builds
# Adam Cockell
# January 2014

# Make sure this is run from inside of the repository that you clone

platform=($(echo $1 | awk '{print tolower($0)}'))
for_app=$2
for_version=$3
qa_line_a=$4
qa_line_b=$5
feature=$6
build_directory_a=$7
build_directory_b=$8
build_directory_c=$9
original_directory=($(pwd))

set -e

write_app()
{
  VERSION_TESTING=$1
  QA_LINE_A=$2
  QA_LINE_B=$3
  FEATURE=$4

  if [ "$VERSION_TESTING" != "" ]; then
    # clone git repo and checkout older build
    cd $build_directory_a
    [ ! -d temp_build ] || rm -r -f temp_build

    git clone git@github.com:radiumone/r1-effects-sdk-$platform.git temp_build
    cd temp_build

    git checkout $VERSION_TESTING

    if [ "$platform" == "ios" ]; then
      git submodule init
      git submodule update
    fi

    cd $original_directory

    ./build $platform $for_app $build_directory_a $build_directory_a/temp_build ../temp_build/r1-effects-sdk-$platform
    
    cd $build_directory_a
    rm -r -f temp_build

    cd $original_directory
    ./cucumber $platform $for_app build_regression

    # rebuild the sdk
    ./cucumber $platform $for_app $feature $build_directory_a $build_directory_b
  else
    # apply customization to current build
    if [ "$platform" == "ios" ]; then
      echo "Modifying $for_app for line A customization"
      sed "s/QA_LINE_A/$QA_LINE_A/g" "automation/AppDelegateTemplate.m" > "automation/AppDelegateTemplateB.m"

      echo "Modifying $for_app for line B customization"
      cp $build_directory_a/$for_app/AppDelegate.m AppDelegate.m
      sed "s/QA_LINE_B/$QA_LINE_B/g" "automation/AppDelegateTemplateB.m" > $build_directory_a/$for_app/AppDelegate.m
      rm "automation/AppDelegateTemplateB.m"
    else
        echo "Modifying demo for crop selection"
        sed "s/QA_LINE_A/R1PhotoEffectsSDK.$QA_LINE_A/g" automation/MainActivityTemplate.java > automation/MainActivityTemplateB.java
        echo "Modifying demo for effects selection"
        cp $build_directory_a/src/com/example/qa_demo/MainActivity.java MainActivity.java
        sed "s/QA_LINE_B/$QA_LINE_B/g" automation/MainActivityTemplateB.java > $build_directory_a/src/com/example/qa_demo/MainActivity.java
        rm automation/MainActivityTemplateB.java
      fi
    # rebuild the app only
    ./cucumber $platform $for_app $feature $build_directory_a

    # cleanup appdelegate
    if [ "$platform" == "ios" ]; then
      mv AppDelegate.m $build_directory_a/$for_app/AppDelegate.m
      rm -f AppDelegate.m
    else
      mv MainActivity.java $build_directory_a/src/com/example/qa_demo/MainActivity.java
      rm -f MainActivity.java
    fi

  fi
}

write_app "$for_version" "$qa_line_a" "$qa_line_b" "$feature"

if [ $? -gt 0 ]; then
  exit 1
fi
