#!/bin/bash
# Script for validating custom SDK builds
# Adam Cockell
# January 2014

platform=$1
for_app=$2
for_version=$3
build_directory_a=$4
build_directory_b=$5
build_directory_c=$6

write_app()
{
  VERSION_TESTING=$1
  if [ "$VERSION_TESTING" != "" ]; then
    [ ! -d temp_build ] || rm -r -f temp_build
    git clone git@github.com:viame/r1-effects-sdk-ios.git temp_build
    cd temp_build
    git checkout $VERSION_TESTING
    git submodule init
    git submodule update

    cd ..
    ./build $platform $for_app ../../ios-sdk temp_build
    rm -r -f temp_build
    ./cucumber $platform $for_app crop
    ./cucumber $platform $for_app crop ../../ios-sdk ../../ios-sdk
  fi
}

write_app $for_version
