#!/bin/bash
# Script for running cucumber-style features on iOS and Android
# Adam Cockell
# January 2014

platform=$1
for_app=$2
feature=$3
build_directory_a=$4
build_directory_b=$5
build_directory_c=$6

original_directory=($(pwd))

run_instructions="./run [ platform ] [ app_name ] [ all_or_feature_by_name ] [ optional_sdk_or_app_directory ] [ optional_app_directory_if_using_sdk ] [ android_relative_path_to_sdk_from_app ] "

clean_all(){
  if [ -f build.xml ]; then
    rm build.xml
  fi
  if [ -f project.properties ]; then
    rm project.properties
  fi
}

if [[ -z "$platform" ]]; then
  echo "You did not specify a platform."
  echo $run_instructions
  exit
fi

if [[ -z "$for_app" ]]; then
  echo "You did not specify an app name."
  echo $run_instructions
  exit
fi

if [[ -z "$feature" ]]; then
  echo "You did not specify a feature name or all"
  echo $run_instructions
  exit
else
  feature=($(echo $feature | awk '{print tolower($0)}'))
  if [[ ! -f "features/$feature.feature" && $feature != "all" ]]; then
    echo "The feature you specified does not have a .feature file associated with it."
    echo "Feature files should be created in the features directory."
    echo "Scenarios for a feature called 'crop' should be written in features/crop.feature"
    exit
  fi
fi

udid=($(./identify_udid))

echo "Starting automation for $for_app on $udid"

./build $platform $for_app $build_directory_a $build_directory_b $build_directory_c

rm -r www/runs/*

ruby lib/fly_cucumber.rb $platform $udid $for_app $feature
cucumber_errors=$?
for run in www/runs/$udid/*
do
  for sub_directory in $run/*
  do
    if [ -d "$sub_directory" ]; then
      cd "$sub_directory"
      for screenshot in *.png
      do
        if [ -f $screenshot ]; then
          mv $screenshot ../
        fi
      done
      cd $original_directory
    fi
  done
  for pngs in $run/*.png
  do
    if [ -f $pngs ]; then
      echo "<screen name='${pngs##*/}'></screen>" >> "$run/meta.xml"
    fi
  done
  echo "</test>" >> "$run/meta.xml"
done

[ ! -f effects_temp ] || rm effects_temp

cd www
./index.rb -u $udid

open "$udid.html"

if [ "$cucumber_errors" -gt 0 ]; then
  exit 1
fi
