#!/bin/bash
platform=$1
for_app=$2
build_directory_a=$3
build_directory_b=$4
cudid=0

original_directory=pwd

if [[ -z "$platform" ]]; then
  echo "You did not specify a platform."
  echo "./run [ platform ] [ app_name ]"
  exit
fi

if [[ -z "$for_app" ]]; then
  echo "You did not specify an app name."
  echo "./run [ platform] [ app_name ]"
  exit
fi

echo "Making sure we have a connection to a device...We can wait forever here..."
while [ $cudid -eq 0 ]
do
  if [ "$platform" == "ios" ]; then
    udid=($(system_profiler SPUSBDataType | grep -A 10 iP | grep Serial | cut -d: -f2))
    udid=${udid[device_order]}
  else
    udid=($(adb devices | tail -n 2))
    udid=${udid[0]}
    if [ "$udid" == "List" ]; then
      udid=""
    fi
  fi
  cudid=${#udid}
done

udid=${udid// /}
echo "Starting automation for $for_app on $udid"

if [[ -z $build_directory_b ]]; then
  echo "skipping directory B build"
else
  cd $build_directory_b
  xcrun xcodebuild -target R1PhotoEffectsSDK -sdk iphoneos "ARCHS=armv7s armv7" BUILD_NUMBER=${BUILD_NUMBER} IPHONEOS_DEPLOYMENT_TARGET=5.0 clean build
  cd $original_directory
fi

if [[ -z $build_directory_a ]]; then 
  echo "skipping directory A build"
else
  cd $build_directory_a
  xcrun xcodebuild -target Demo -sdk iphoneos "ARCHS=armv7s armv7" clean build CODE_SIGN_IDENTITY="iPhone Developer: Brad Smith (YE9V76353E)"
  "test/fruitstrap" -i $udid -b build/Release-iphoneos/Demo.app
  cd $original_directory
fi

rm -r www/runs/*

ruby fly_cucumber.rb $platform $udid $for_app

echo "Preparing results"

current_directory=($(pwd))

for run in www/runs/$udid/*
do
  for sub_directory in $run/*
  do
    if [ -d "$sub_directory" ]; then
      cd "$sub_directory"
      for screenshot in *.png
      do
        if [ -f $screenshot ]; then
          echo $screenshot
          mv $screenshot ../
        fi
      done
      cd $current_directory
    fi
  done
  for pngs in $run/*.png
  do
    if [ -f $pngs ]; then
      echo "<screen name='${pngs##*/}'></screen>" >> "$run/meta.xml"
    fi
  done
  echo "</test>" >> "$run/meta.xml"
done


cd www
./index.rb

open "$udid.html"
