#!/bin/bash
platform=$1
for_app=$2
cudid=0

if [[ -z "$platform" ]]; then
  echo "You did not specify a platform."
  echo "./run [ platform ] [ app_name ]"
  exit
fi

if [[ -z "$for_app" ]]; then
  echo "You did not specify an app name."
  echo "./run [ platform] [ app_name ]"
  exit
fi

echo "Making sure we have a connection to a device...We can wait forever here..."
while [ $cudid -eq 0 ]
do
  if [ "$platform" == "ios" ]; then
    udid=($(system_profiler SPUSBDataType | grep -A 10 iP | grep Serial | cut -d: -f2))
    udid=${udid[device_order]}
  else
    udid=($(adb devices | tail -n 2))
    udid=${udid[0]}
    if [ "$udid" == "List" ]; then
      udid=""
    fi
  fi
  cudid=${#udid}
done

udid=${udid// /}
echo "Starting automation for $for_app on $udid"

ruby fly_cucumber.rb $platform $udid $for_app
