#!/bin/bash
# Script for identifying ios and android device IDs
# Adam Cockell
# January 2014

platform=($(echo $1 | awk '{print tolower($0)}'))
cudid=0


while [ $cudid -eq 0 ]
do
  if [ "$platform" == "ios" ]; then
    udid=($(system_profiler SPUSBDataType | grep -A 10 iP | grep Serial | cut -d: -f2))
    udid=${udid[device_order]}
  else
    udid=($(adb devices | tail -n 2))
    udid=${udid[0]}
    if [ "$udid" == "List" ]; then
      udid=""
    fi
  fi
  cudid=${#udid}
done

udid=${udid// /}

echo $udid
